// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace Weather_DI_DataStructures
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Properties
    {
        private string[] _Periods = new string[] { };

        public string[] aPeriods
        {
            get { return _Periods; }
            set { _Periods = value; }
        }

    }

    public class Periods
    {
        private int _LocationID = 0;
        private string _DataType = "";
        private string _LocationName = "";
        private int _PeriodNumber = 0;
        private string _PeriodName = "";
        private string _StartTime = "";
        private string _EndTime = "";
        private bool _IsDayTime = false;
        private int _Temperature = 0;
        private string _TemperatureUnit = "";
        private string _TemperatureTrend = "";
        private string _WindSpeed = "";
        private string _WindDirection = "";
        private string _Icon = "";
        private string _ShortForecast = "";
        private string _DetailedForecast = "";

        public int LocationID
        {
            get { return _LocationID; }
            set { _LocationID = value; }
        }
        public string DataType
        {
            get { return _DataType; }
            set { _DataType = value; }
        }

        public string LocationName
        {
            get { return _LocationName; }
            set { _LocationName = value; }
        }
        public int PeriodNumber
        {
            get { return _PeriodNumber; }
            set { _PeriodNumber = value; }
        }

        public string PeriodName
        {
            get { return _PeriodName; }
            set { _PeriodName = value; }
        }

        public string StartTime
        {
            get { return _StartTime; }
            set { _StartTime = value; }
        }

        public string EndTime
        {
            get { return _EndTime; }
            set { _EndTime = value; }
        }

        public bool IsDayTime
        {
            get { return _IsDayTime; }
            set { _IsDayTime = value; }
        }

        public int Temperature
        {
            get { return _Temperature; }
            set { _Temperature = value; }
        }

        public string TemperatureUnit
        {
            get { return _TemperatureUnit; }
            set { _TemperatureUnit = value; }
        }

        public string TemperatureTrend
        {
            get { return _TemperatureTrend; }
            set { _TemperatureTrend = value; }
        }

        public string WindSpeed
        {
            get { return _WindSpeed; }
            set { _WindSpeed = value; }
        }

        public string WindDirection
        {
            get { return _WindDirection; }
            set { _WindDirection = value; }
        }

        public string Icon
        {
            get { return _Icon; }
            set { _Icon = value; }
        }

        public string ShortForecast
        {
            get { return _ShortForecast; }
            set { _ShortForecast = value; }
        }

        public string DetailedForecast
        {
            get { return _DetailedForecast; }
            set { _DetailedForecast = value; }
        }
    }
}
